package com.excalibur.stock.stockservice.controller;

import com.excalibur.stock.stockservice.model.Stock;
import com.excalibur.stock.stockservice.repository.StockRepository;
import com.excalibur.stock.stockservice.service.IStockService;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StockRepository stockRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@RequestParam String ticker, @RequestParam String company_name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Stock n = new Stock();
        n.setTicker(ticker);
        n.setCompany_name(company_name);
        stockRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Stock> getAllUsers() {
        // This returns a JSON or XML with the users
        return stockRepository.findAll();
    }
}